### ISSUE TITLE
importing molecules not working as expected

### ISSUE THREAD

**Issue by hamed-musallam** [cheminfo/nmr-load-save#118]
We have a bug in nmr-load-save package  and NMRium 

[https://cloud.uni-jena.de/s/y72GbCX8bJbmpJT/download/10.zip](  https://cloud.uni-jena.de/s/y72GbCX8bJbmpJT/download/10.zip
)  

1- when i use `readFromFileArray` it returns a strange result, as you can see we have two molecules, it seems that they are duplicated because have the same label which should be unique.

```
{
    id: 'f0014f59-f731-4d0d-bf08-ebd260f8d74a',
    molfile: ' ',
    label: 'p#'
  },
  {
    id: '014f59f7-31fd-4d7f-88eb-d260f8d74afe',
    molfile: '\x00\x05\x16\x07\x00\x02\x00\x00Mac OS X        \x00\x02\x00\x00\x00\t\x00\x00\x002\x00\x00\x00�\x00\x00\x00\x02\x00\x00\x00�\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00ATTR\x00\x00\x00\x00\x00\x00\x00�\x00\x00\x00�\x00\x00\x00>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00�\x00\x00\x00>\x00\x00\x15com.apple.quarantine\x00q/0081;62dff8b4;sharingd;2AFFE0C2-0E7F-4C3B-9111-6C98B4663661\x00',
    label: 'p#'
  }
```

2- if I drag and drop the file, NMRium not loading any molecules, we should have one

![image](https://user-images.githubusercontent.com/35760236/216590077-89a63bc2-ad0e-43b9-b30b-cb99488b871f.png)

**Comment by lpatiny** [comment]
What is clear is that this structure.mol file is empty.

If I check `grep -r "Mac OS X"` there is no hit.

I wonder where this molfile is coming from but not present in the zip file you uploaded.

    id: '014f59f7-31fd-4d7f-88eb-d260f8d74afe',
    molfile: '\x00\x05\x16\x07\x00\x02\x00\x00Mac OS X        \x00\x02\x00\x00\x00\t\x00\x00\x002\x00\x00\x00�\x00\x00\x00\x02\x00\x00\x00�\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00ATTR\x00\x00\x00\x00\x00\x00\x00�\x00\x00\x00�\x00\x00\x00>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00�\x00\x00\x00>\x00\x00\x15com.apple.quarantine\x00q/0081;62dff8b4;sharingd;2AFFE0C2-0E7F-4C3B-9111-6C98B4663661\x00',
    label: 'p#'
