### ISSUE TITLE
Canonize molfile

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-load-save#120]
When we are loading molfile we should canonize it in order to be able to have the right atom numbers.

I would also expand all the hydrogens because we often need to assign the hydrogens.

This can achieved by:
- molecule.addImplicitHydrogens()
- molecule.toMolfile()

For now we should just keep this molfile and send it to NMRium. We will see later if we need to keep the original molfile or not.

**Comment by jobo322** [comment]
it was done by 18bd6f42907de88b006f8167378923850699c2f1
