### ISSUE TITLE
Useless generic

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-load-save#134]
In those lines:

https://github.com/cheminfo/nmr-load-save/blob/d43d204fbaf0f919d0c257c1b4f3723913757dcd/src/save/serializeNmriumState.ts#L43-L51

The use of generic is useless and it is the same as:

```
export function serializeNmriumState(
  nmriumState: NmriumState,
  options: GetNmriumStateOptions,
```

That is more clear.

**Comment by jobo322** [comment]
close by 018e0a5948f0891d26c20e541553bdcc133162ec
