### ISSUE TITLE
Enable nmr-load-save to be used within a nodejs project (browser independent)

### ISSUE THREAD

**Issue by CS76** [cheminfo/nmr-load-save#22]
To use the converting capabilities of the nmr-load-save package for bulk conversions and automation, the package needs to be used within a nodejs project (REST API).

**Comment by hamed-musallam** [comment]
@CS76 @lpatiny 

it seems we need to expose another function from filelist-utils to create a fileCollection from ArrayBuffer, without it, we can not use the read function from nmr-load-save.

**Comment by jobo322** [comment]
@hamed-musallam  do you know if it is solved with the fileCollectionFromWebservice function?

**Comment by hamed-musallam** [comment]
@jobo322 

yes it should solve our problem but for now, we create a fileCollection based on the way how it is done in fileCollectionFromWebservice function
