### ISSUE TITLE
Exported processed/real spectrum is inverted in c6h6.org

### ISSUE THREAD

**Issue by jobo322** [cheminfo/nmr-load-save#222]
it does not happen exporting complex data.
![realExportation](https://github.com/cheminfo/nmr-load-save/assets/12143935/0795ba9a-d5d9-4734-9a1d-cb3dadd5ddfb)

**Comment by michelgravel** [comment]
But I see the same thing happening in your example:
- Scale in c6h6.org displays as 0 to -7 ppm instead of ~10 to ~0 ppm.
- Spectrum displays from upfield to downfield instead of the conventional way (downfield to upfield).
Is that something that the user can fix in c6h6.org?
