### ISSUE TITLE
Load integrals from Bruker files

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-load-save#252]
If integrals.txt are available we need to convert this file to 'integrals'.

In order to set the relative intensity I would use 2 different approaches:
1. If one of the integral as the value 1.0000 take care that the relativeIntegral of this integral keeps this 1.0000
2. Otherwise, take care that the sum of the relativeIntegrals are identical.

![image](https://github.com/cheminfo/nmr-load-save/assets/1484241/04520d5a-a340-406d-87cb-bfa1a6d2b210)

**Comment by jobo322** [comment]
it was done by 9a0b5a02aab476fa2c119138b22f432053001136
