### ISSUE TITLE
File version migration problem ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-load-save#253]
We are no longer able to load this file.

- https://cheminfo.github.io/nmr-dataset-demo/coffee/coffee.nmrium

Only spectrum 7 appears:

![image](https://github.com/cheminfo/nmr-load-save/assets/1484241/af2b9a4f-fa77-4add-8203-5a213c333494)

**Comment by jobo322** [comment]
the nmrium file was wrong
