### ISSUE TITLE
Remove zip from this library ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-load-save#35]
I'm wondering why this code exists ?

https://github.com/cheminfo/nmr-load-save/blob/376af599e09cd8c8d7d08840775144b2053eb7c2/src/reader/readZip.ts#L17-L22

Unzipping is done by default transparently in `filelist-utils` thanks to the ExpandOptions (by default we unzip and ungzip): https://github.com/cheminfo/filelist-utils/blob/main/src/fileCollectionFromFileList.ts#L17-L20

If it is a problem to have zip inside zip we should discuss about it.

**Comment by jobo322** [comment]
so, the `.zip` extension will be removed. We should think about a zip/gzip file inside of a zip/gzip file, it will be filtered out.

**Comment by jobo322** [comment]
even better, we could generate internally a fileCollection from the zip/ungzip file. what do you think?
