### ISSUE TITLE
Prediction returned by `predictAllSpectra` no longer compatible with `nmr-load-save`

### ISSUE THREAD

**Issue by targos** [cheminfo/nmr-load-save#74]
NMRium predict page is broken: https://www.nmrium.org/predict?smiles=c1ccccc1CC

![image](https://user-images.githubusercontent.com/2352663/204842671-2082c931-8a52-4819-904d-78fc899501c3.png)

I don't know if the problem is in this project or nmr-load-save, though.

**Comment by targos** [comment]
`spectrum.source` should be optional.

**Comment by jobo322** [comment]
I'm not able to reproduce the error, could you test the prediction in https://github.com/cheminfo/nmrium/pull/1971

**Comment by jobo322** [comment]
`predictAll` returns signals and zones, the spectra is generated by `signalsToXY` or `signals2DToZ` for 2D data. the structure of nmrium like object is initialized inside of nmrium and it was adapted recently to use quadrants from experimental 2D spectra by https://github.com/cheminfo/nmrium/pull/1971/commits/65668a508f32a163a1c2bdfd25216de1dd83641b

**Comment by hamed-musallam** [comment]
@jobo322 

Michael is right the ```spectrum.source``` should be optional

**Comment by jobo322** [comment]
there is a way to reproduce the error using a local deployment? I would like to know why it is checking for JCAMP-DX for a prediction

**Comment by jobo322** [comment]
it http://localhost:3000/predict?smiles=c1ccccc1CC does not work

**Comment by targos** [comment]
> it http://localhost:3000/predict?smiles=c1ccccc1CC does not work

Yes, exactly. That's why I opened this issue.

**Comment by hamed-musallam** [comment]
@targos @jobo322 

let me check this from the side of NMRium, i think this ticket should be moved there

**Comment by lpatiny** [comment]
This .nmrium file is currently not working because the 'source' property is not present.

This one should anyway work

[nosource.nmrium.zip](https://github.com/cheminfo/nmr-load-save/files/10132557/nosource.nmrium.zip)

**Comment by jobo322** [comment]
> This .nmrium file is currently not working because the 'source' property is not present.
> 
> This one should anyway work
> 
> [nosource.nmrium.zip](https://github.com/cheminfo/nmr-load-save/files/10132557/nosource.nmrium.zip)

@lpatiny, should we append the necessary information into the `info`. Because this file has only data property.

**Comment by lpatiny** [comment]
Indeed my file is corrupted. We can not guess the frequency, if it is an FID. So this file has to fail, this is correct.

But `source` is optional IF info with `frequency ....` are present.

**Comment by jobo322** [comment]
it is done by 68621927014043c6a97c57b749d1404393bc040a, the same effect is on nmrium by https://github.com/cheminfo/nmrium/commit/1f9aa4d7fd35f82f8eaf074b2e3ed482c96d9bde
