### ISSUE TITLE
Allow '.dx' '.jdx' and '.jcamp' as file extension

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-load-save#85]

**Comment by hamed-musallam** [comment]
@jobo322 

you point to the Jcamp extension here  https://github.com/cheminfo/nmr-load-save/blob/1b3cda591199b86ca2c6670af9844f5c2bccbe57/src/reader/read.ts#L149 but it is not listed in the  FILES_TYPES https://github.com/cheminfo/nmr-load-save/blob/master/src/utilities/files/constants.ts#L1-L10

**Comment by hamed-musallam** [comment]
@jobo322 

I think it is better to convert it to `enum` or you can still use the FILE_TYPES as it but it should be `read only`.  you use `const` which means we can`t assign new values to FILE_TYPES  but we still can set a new value to the inner object if some use it in a wrong way
